#端口配置
server:
  port: 30809

#数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.96.253.29:8801/smt_bss_cpc2?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpc_user
    password: cpc_user_123





#spring:
#  jta:
#    enabled: true
#    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
#    max-actives: 200
#    enable-logging: false
#    atomikos:
#      datasource:
#          unique-resource-name: dataSource
#          xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
#          xa-properties:
#            driverClassName: com.mysql.jdbc.Driver
#            url: jdbc:mysql://47.94.168.117:3306/fpc_system?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#            username: root
#            password: Yanlei2018
#      datasource_prd:
#          unique-resource-name: datasourcePrd
#          xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
#          xa-properties:
#            driverClassName: com.mysql.jdbc.Driver
#            url: jdbc:mysql://47.94.168.117:3306/cpct?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#            username: root
#            password: root
#

  #redis相关配置
  redis:
    host: 47.94.168.117
    port: 6379
    password: 9bOCHtdJkNZ1hb2e35OmgIrLvGEaBXuT2udRBQNt5VQ
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000
  #ES
#  elasticsearch:
#      ip: 134.108.3.30
#      port: 9300
#      pool: 5
#      cluster:
#        name: es-cpct

# cpct_pst_topic 下二個分組 producerGroupName  producerGroupName2
# cpct_push_end_topic 1個分組 pushGroupName : cpct_push_end_consumer
ctg:
  namesrvAddr: 134.108.6.201:9876;134.108.6.202:9876;134.108.6.203:9876
  cpctGroupName: cpct_detailed_list_group_gray
  namesrvAuthID: cpct_user
  namesrvAuthPwd: Cpct!@3e#
  consumeOrderly: false
  instanceName: prod_cpct
  maxMessageSize: 8242880
  sendMaxRetryTimes: 2
  sendMsgTimeout: 30000
  compressMsgBodyOverHowmuch: 4098
  clientWorkerThreads : 4
  clusterName: CRM_MQ
  tenantID: 2
  cpctTopic: cpct_detailed_list_topic_gray


  # 第四topic es日志添加队列中转
  cpctEsLogTopic: cpct_eslog_prod
  cpctEsLogGroup: cpct_eslog_group_gray



